version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'laravelapp'
    container_name: laravel_app
    ports:
      - 8181:8181
    volumes:
      - ./:/app
  # database
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: laravel_db
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_PASSWORD: root
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 
  #Volumes
volumes:
  dbdata:
    driver: local